### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by javiavid** [trucke/para-workflower#1]
I usually have attached notes or extra material in each project and it would be saved in the folder of the same name. This way if I need to resume a project I have everything organized quickly.

Is it possible to make the plugin compatible with a folder structure so that when creating a new project, area or resource a folder is created and inside a note with the same name as the folder?

Also if a project is archived the entire folder should be moved.

**Comment by trucke** [comment]
Hi @javiavid,

Thanks for your input. I have already thought about this. Creating a folder for the project is more in line with the PARA methodology. 

I, personally, like it to use a flat structure that's why the first officially release of the plugin looks like this.

ICYMI, the areas are already created with an companion folder. However, the area note itself is not located in this folder. The reason for this is that you have faster and more direct access to your area with fewer clicks. The files in the companion folder are automatically linked in the area note when using my builtin template.

For the resources, I don't plan to support a folder structure for now. A flat structure offers you an more unbiased view of your resources and possibly new incentives if you are looking for something. 
As an alternative for the moment, Obsidian supports tags, searches and filters, which are powerful tools and are sufficient to categorize and find a specific resource or group of resources.

For the projects, I will definitely take a look to make the plugin compatible with a folder structure like you mentioned.

There are also some other things I want to do and fix. In the coming days I will update the README to keep you all informed about the further development of the plugin.

This plugin is yet in an early stage of development and any feedback and ideas are very welcome.

I hope I could give you some insights and a better understanding of the current development.
Let me know if you have any further questions.

**Comment by javiavid** [comment]
Thank you for your comments.  I will be attentive to the development of the plugin.

**Comment by trucke** [comment]
Want to let you know that support for a folder structure for projects is on the way and will be available with the next plugin release 👍
#3

**Comment by javiavid** [comment]
Thanks!
